name: Deploy Docusaurus to GitHub Pages

on:
    push:
    pull_request:
  
jobs:
    deploy:
        name: Deploy to GitHub Page
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Install dependencies
              run: |
                  cd website-docs
                  yarn install --frozen-lockfile

            - name: Build Docusaurus website
              run: |
                  cd website-docs
                  yarn run build

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./website-docs/build
                  user_name: 'github-actions[bot]'
                  user_email: 'github-actions[bot]@users.noreply.github.com'
                  commit_message: 'chore: deploy documentation website [skip ci]'
                  enable_jekyll: false
                  full_commit_message: |
                      chore: deploy documentation website [skip ci]
                      Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
